# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.31

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/lilianbazantay/delivery/3eme_annee/r-type

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/lilianbazantay/delivery/3eme_annee/r-type

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/lilianbazantay/delivery/3eme_annee/r-type/CMakeFiles /home/lilianbazantay/delivery/3eme_annee/r-type//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/lilianbazantay/delivery/3eme_annee/r-type/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -P /home/lilianbazantay/delivery/3eme_annee/r-type/CMakeFiles/VerifyGlobs.cmake
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named r-type_client

# Build rule for target.
r-type_client: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 r-type_client
.PHONY : r-type_client

# fast build rule for target.
r-type_client/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/r-type_client.dir/build.make CMakeFiles/r-type_client.dir/build
.PHONY : r-type_client/fast

#=============================================================================
# Target rules for targets named r-type_server

# Build rule for target.
r-type_server: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 r-type_server
.PHONY : r-type_server

# fast build rule for target.
r-type_server/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/r-type_server.dir/build.make CMakeFiles/r-type_server.dir/build
.PHONY : r-type_server/fast

#=============================================================================
# Target rules for targets named debug

# Build rule for target.
debug: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 debug
.PHONY : debug

# fast build rule for target.
debug/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/debug.dir/build.make CMakeFiles/debug.dir/build
.PHONY : debug/fast

#=============================================================================
# Target rules for targets named re

# Build rule for target.
re: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 re
.PHONY : re

# fast build rule for target.
re/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/re.dir/build.make CMakeFiles/re.dir/build
.PHONY : re/fast

src/client/Asio.o: src/client/Asio.cpp.o
.PHONY : src/client/Asio.o

# target to build an object file
src/client/Asio.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/r-type_client.dir/build.make CMakeFiles/r-type_client.dir/src/client/Asio.cpp.o
.PHONY : src/client/Asio.cpp.o

src/client/Asio.i: src/client/Asio.cpp.i
.PHONY : src/client/Asio.i

# target to preprocess a source file
src/client/Asio.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/r-type_client.dir/build.make CMakeFiles/r-type_client.dir/src/client/Asio.cpp.i
.PHONY : src/client/Asio.cpp.i

src/client/Asio.s: src/client/Asio.cpp.s
.PHONY : src/client/Asio.s

# target to generate assembly for a file
src/client/Asio.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/r-type_client.dir/build.make CMakeFiles/r-type_client.dir/src/client/Asio.cpp.s
.PHONY : src/client/Asio.cpp.s

src/client/PacketCodec.o: src/client/PacketCodec.cpp.o
.PHONY : src/client/PacketCodec.o

# target to build an object file
src/client/PacketCodec.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/r-type_client.dir/build.make CMakeFiles/r-type_client.dir/src/client/PacketCodec.cpp.o
.PHONY : src/client/PacketCodec.cpp.o

src/client/PacketCodec.i: src/client/PacketCodec.cpp.i
.PHONY : src/client/PacketCodec.i

# target to preprocess a source file
src/client/PacketCodec.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/r-type_client.dir/build.make CMakeFiles/r-type_client.dir/src/client/PacketCodec.cpp.i
.PHONY : src/client/PacketCodec.cpp.i

src/client/PacketCodec.s: src/client/PacketCodec.cpp.s
.PHONY : src/client/PacketCodec.s

# target to generate assembly for a file
src/client/PacketCodec.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/r-type_client.dir/build.make CMakeFiles/r-type_client.dir/src/client/PacketCodec.cpp.s
.PHONY : src/client/PacketCodec.cpp.s

src/client/client.o: src/client/client.cpp.o
.PHONY : src/client/client.o

# target to build an object file
src/client/client.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/r-type_client.dir/build.make CMakeFiles/r-type_client.dir/src/client/client.cpp.o
.PHONY : src/client/client.cpp.o

src/client/client.i: src/client/client.cpp.i
.PHONY : src/client/client.i

# target to preprocess a source file
src/client/client.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/r-type_client.dir/build.make CMakeFiles/r-type_client.dir/src/client/client.cpp.i
.PHONY : src/client/client.cpp.i

src/client/client.s: src/client/client.cpp.s
.PHONY : src/client/client.s

# target to generate assembly for a file
src/client/client.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/r-type_client.dir/build.make CMakeFiles/r-type_client.dir/src/client/client.cpp.s
.PHONY : src/client/client.cpp.s

src/client/graphical/Game.o: src/client/graphical/Game.cpp.o
.PHONY : src/client/graphical/Game.o

# target to build an object file
src/client/graphical/Game.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/r-type_client.dir/build.make CMakeFiles/r-type_client.dir/src/client/graphical/Game.cpp.o
.PHONY : src/client/graphical/Game.cpp.o

src/client/graphical/Game.i: src/client/graphical/Game.cpp.i
.PHONY : src/client/graphical/Game.i

# target to preprocess a source file
src/client/graphical/Game.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/r-type_client.dir/build.make CMakeFiles/r-type_client.dir/src/client/graphical/Game.cpp.i
.PHONY : src/client/graphical/Game.cpp.i

src/client/graphical/Game.s: src/client/graphical/Game.cpp.s
.PHONY : src/client/graphical/Game.s

# target to generate assembly for a file
src/client/graphical/Game.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/r-type_client.dir/build.make CMakeFiles/r-type_client.dir/src/client/graphical/Game.cpp.s
.PHONY : src/client/graphical/Game.cpp.s

src/client/graphical/InputManager.o: src/client/graphical/InputManager.cpp.o
.PHONY : src/client/graphical/InputManager.o

# target to build an object file
src/client/graphical/InputManager.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/r-type_client.dir/build.make CMakeFiles/r-type_client.dir/src/client/graphical/InputManager.cpp.o
.PHONY : src/client/graphical/InputManager.cpp.o

src/client/graphical/InputManager.i: src/client/graphical/InputManager.cpp.i
.PHONY : src/client/graphical/InputManager.i

# target to preprocess a source file
src/client/graphical/InputManager.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/r-type_client.dir/build.make CMakeFiles/r-type_client.dir/src/client/graphical/InputManager.cpp.i
.PHONY : src/client/graphical/InputManager.cpp.i

src/client/graphical/InputManager.s: src/client/graphical/InputManager.cpp.s
.PHONY : src/client/graphical/InputManager.s

# target to generate assembly for a file
src/client/graphical/InputManager.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/r-type_client.dir/build.make CMakeFiles/r-type_client.dir/src/client/graphical/InputManager.cpp.s
.PHONY : src/client/graphical/InputManager.cpp.s

src/client/graphical/Window.o: src/client/graphical/Window.cpp.o
.PHONY : src/client/graphical/Window.o

# target to build an object file
src/client/graphical/Window.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/r-type_client.dir/build.make CMakeFiles/r-type_client.dir/src/client/graphical/Window.cpp.o
.PHONY : src/client/graphical/Window.cpp.o

src/client/graphical/Window.i: src/client/graphical/Window.cpp.i
.PHONY : src/client/graphical/Window.i

# target to preprocess a source file
src/client/graphical/Window.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/r-type_client.dir/build.make CMakeFiles/r-type_client.dir/src/client/graphical/Window.cpp.i
.PHONY : src/client/graphical/Window.cpp.i

src/client/graphical/Window.s: src/client/graphical/Window.cpp.s
.PHONY : src/client/graphical/Window.s

# target to generate assembly for a file
src/client/graphical/Window.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/r-type_client.dir/build.make CMakeFiles/r-type_client.dir/src/client/graphical/Window.cpp.s
.PHONY : src/client/graphical/Window.cpp.s

src/client/graphical/main.o: src/client/graphical/main.cpp.o
.PHONY : src/client/graphical/main.o

# target to build an object file
src/client/graphical/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/r-type_client.dir/build.make CMakeFiles/r-type_client.dir/src/client/graphical/main.cpp.o
.PHONY : src/client/graphical/main.cpp.o

src/client/graphical/main.i: src/client/graphical/main.cpp.i
.PHONY : src/client/graphical/main.i

# target to preprocess a source file
src/client/graphical/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/r-type_client.dir/build.make CMakeFiles/r-type_client.dir/src/client/graphical/main.cpp.i
.PHONY : src/client/graphical/main.cpp.i

src/client/graphical/main.s: src/client/graphical/main.cpp.s
.PHONY : src/client/graphical/main.s

# target to generate assembly for a file
src/client/graphical/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/r-type_client.dir/build.make CMakeFiles/r-type_client.dir/src/client/graphical/main.cpp.s
.PHONY : src/client/graphical/main.cpp.s

src/client/main.o: src/client/main.cpp.o
.PHONY : src/client/main.o

# target to build an object file
src/client/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/r-type_client.dir/build.make CMakeFiles/r-type_client.dir/src/client/main.cpp.o
.PHONY : src/client/main.cpp.o

src/client/main.i: src/client/main.cpp.i
.PHONY : src/client/main.i

# target to preprocess a source file
src/client/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/r-type_client.dir/build.make CMakeFiles/r-type_client.dir/src/client/main.cpp.i
.PHONY : src/client/main.cpp.i

src/client/main.s: src/client/main.cpp.s
.PHONY : src/client/main.s

# target to generate assembly for a file
src/client/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/r-type_client.dir/build.make CMakeFiles/r-type_client.dir/src/client/main.cpp.s
.PHONY : src/client/main.cpp.s

src/client/parser.o: src/client/parser.cpp.o
.PHONY : src/client/parser.o

# target to build an object file
src/client/parser.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/r-type_client.dir/build.make CMakeFiles/r-type_client.dir/src/client/parser.cpp.o
.PHONY : src/client/parser.cpp.o

src/client/parser.i: src/client/parser.cpp.i
.PHONY : src/client/parser.i

# target to preprocess a source file
src/client/parser.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/r-type_client.dir/build.make CMakeFiles/r-type_client.dir/src/client/parser.cpp.i
.PHONY : src/client/parser.cpp.i

src/client/parser.s: src/client/parser.cpp.s
.PHONY : src/client/parser.s

# target to generate assembly for a file
src/client/parser.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/r-type_client.dir/build.make CMakeFiles/r-type_client.dir/src/client/parser.cpp.s
.PHONY : src/client/parser.cpp.s

src/ecs/main.o: src/ecs/main.cpp.o
.PHONY : src/ecs/main.o

# target to build an object file
src/ecs/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/r-type_client.dir/build.make CMakeFiles/r-type_client.dir/src/ecs/main.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/r-type_server.dir/build.make CMakeFiles/r-type_server.dir/src/ecs/main.cpp.o
.PHONY : src/ecs/main.cpp.o

src/ecs/main.i: src/ecs/main.cpp.i
.PHONY : src/ecs/main.i

# target to preprocess a source file
src/ecs/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/r-type_client.dir/build.make CMakeFiles/r-type_client.dir/src/ecs/main.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/r-type_server.dir/build.make CMakeFiles/r-type_server.dir/src/ecs/main.cpp.i
.PHONY : src/ecs/main.cpp.i

src/ecs/main.s: src/ecs/main.cpp.s
.PHONY : src/ecs/main.s

# target to generate assembly for a file
src/ecs/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/r-type_client.dir/build.make CMakeFiles/r-type_client.dir/src/ecs/main.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/r-type_server.dir/build.make CMakeFiles/r-type_server.dir/src/ecs/main.cpp.s
.PHONY : src/ecs/main.cpp.s

src/server/main.o: src/server/main.cpp.o
.PHONY : src/server/main.o

# target to build an object file
src/server/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/r-type_server.dir/build.make CMakeFiles/r-type_server.dir/src/server/main.cpp.o
.PHONY : src/server/main.cpp.o

src/server/main.i: src/server/main.cpp.i
.PHONY : src/server/main.i

# target to preprocess a source file
src/server/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/r-type_server.dir/build.make CMakeFiles/r-type_server.dir/src/server/main.cpp.i
.PHONY : src/server/main.cpp.i

src/server/main.s: src/server/main.cpp.s
.PHONY : src/server/main.s

# target to generate assembly for a file
src/server/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/r-type_server.dir/build.make CMakeFiles/r-type_server.dir/src/server/main.cpp.s
.PHONY : src/server/main.cpp.s

src/server/parser.o: src/server/parser.cpp.o
.PHONY : src/server/parser.o

# target to build an object file
src/server/parser.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/r-type_server.dir/build.make CMakeFiles/r-type_server.dir/src/server/parser.cpp.o
.PHONY : src/server/parser.cpp.o

src/server/parser.i: src/server/parser.cpp.i
.PHONY : src/server/parser.i

# target to preprocess a source file
src/server/parser.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/r-type_server.dir/build.make CMakeFiles/r-type_server.dir/src/server/parser.cpp.i
.PHONY : src/server/parser.cpp.i

src/server/parser.s: src/server/parser.cpp.s
.PHONY : src/server/parser.s

# target to generate assembly for a file
src/server/parser.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/r-type_server.dir/build.make CMakeFiles/r-type_server.dir/src/server/parser.cpp.s
.PHONY : src/server/parser.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... debug"
	@echo "... re"
	@echo "... r-type_client"
	@echo "... r-type_server"
	@echo "... src/client/Asio.o"
	@echo "... src/client/Asio.i"
	@echo "... src/client/Asio.s"
	@echo "... src/client/PacketCodec.o"
	@echo "... src/client/PacketCodec.i"
	@echo "... src/client/PacketCodec.s"
	@echo "... src/client/client.o"
	@echo "... src/client/client.i"
	@echo "... src/client/client.s"
	@echo "... src/client/graphical/Game.o"
	@echo "... src/client/graphical/Game.i"
	@echo "... src/client/graphical/Game.s"
	@echo "... src/client/graphical/InputManager.o"
	@echo "... src/client/graphical/InputManager.i"
	@echo "... src/client/graphical/InputManager.s"
	@echo "... src/client/graphical/Window.o"
	@echo "... src/client/graphical/Window.i"
	@echo "... src/client/graphical/Window.s"
	@echo "... src/client/graphical/main.o"
	@echo "... src/client/graphical/main.i"
	@echo "... src/client/graphical/main.s"
	@echo "... src/client/main.o"
	@echo "... src/client/main.i"
	@echo "... src/client/main.s"
	@echo "... src/client/parser.o"
	@echo "... src/client/parser.i"
	@echo "... src/client/parser.s"
	@echo "... src/ecs/main.o"
	@echo "... src/ecs/main.i"
	@echo "... src/ecs/main.s"
	@echo "... src/server/main.o"
	@echo "... src/server/main.i"
	@echo "... src/server/main.s"
	@echo "... src/server/parser.o"
	@echo "... src/server/parser.i"
	@echo "... src/server/parser.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -P /home/lilianbazantay/delivery/3eme_annee/r-type/CMakeFiles/VerifyGlobs.cmake
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

