name: Create a new feature request
title: "Quick description"
description: request a new feature here
projects: "r-type"
body:
  - type: textarea
    id: feature_description
    attributes:
      label: Describe the feature
      description: A clear and concise description of what the feature is.
      placeholder: "ex: Add new button to the homepage."
    validations:
      required: true
  - type: textarea
    attributes:
      label: Additional context
      description: Add any other context about the problem here.
      placeholder: |
        ex:
        - Possible implementation ideas
        - Resources
        - Screenshots
        - Any other relevant information.