name: Create a refactor request
title: "Quick description"
description: request a refactor here
projects: "r-type"
body:
  - type: textarea
    id: refactor_description
    attributes:
      label: Describe the refactor
      description: A clear and concise description of what the refactor is.
      placeholder: "ex: Modify the button component for better accessibility."
    validations:
      required: true
  - type: textarea
    attributes:
      label: Additional context
      description: Add any other context about the problem here.
      placeholder: |
        ex:
        - Possible implementation ideas
        - Resources
        - Screenshots
        - Any other relevant information.
